### ISSUE TITLE
Demo not working properly with Create-React-App

### ISSUE THREAD

**Issue by MatteoGioioso** [imgly/pesdk-react-demo#9] opened 2019-02-18 07:43 UTC
1- First of all, this is a React Demo, why the import statement is commented out?
```
import PhotoEditorUI from 'photoeditorsdk/desktop-ui'
//import PhotoEditorUI from 'photoeditorsdk/react-ui'
```

If I try to un-comment and load the css, the all SDK is not working, I got blank screen with no error
https://codesandbox.io/s/r01qv5w35n

```
import PhotoEditorUI from 'photoeditorsdk/react-ui'
import 'photoeditorsdk/css/PhotoEditorSDK.UI.ReactUI.css'
```

2-  Assets baseUrl:

```
assets={{
        baseUrl: 'node_modules/photoeditorsdk/assets'
}}
```
All the assets fails to load in CRA.
just substitute `react-ui` with the `desktop-ui` : https://codesandbox.io/s/r01qv5w35n

**Comment by AndyNeale** [comment] 2019-03-26 10:58
I got round this by downloading all of the assets and storing a copy locally (e.g. our app has a `libs` folder for third-party bits and pieces, so we downloaded the latest zip ([https://github.com/imgly/pesdk-html5-build/archive/v4.16.1.zip](https://github.com/imgly/pesdk-html5-build/archive/v4.16.1.zip) and copied the contents of the `assets` folder to `lib\photoeditorsk`, and then rendered the component using `assets={{ baseURL: 'lib/photoeditorsdk' }}` - it's not a particularly elegant solution, but it _does_ work.

**Comment by keiwando** [comment] 2019-03-26 12:57
@AndyNeale Yes, that is currently the fastest solution in order to get the PhotoEditorSDK working with create-react-app. 

The issue is that create-react-app's default Webpack configuration doesn't automatically copy any assets from the node_modules folders into the build, so you either have to manually place the assets in a location that will be included in the build, or overwrite the Webpack config to also include the assets path in the /node_modules/photoeditorsdk package directory.

**Closed by keiwando** 2019-03-26 12:57 UTC
